### ISSUE TITLE
Not sure if this is because of StevesAddons but it has only started after it was added

### ISSUE THREAD

**Issue by AoKMiKeY** [hilburn/StevesAddons#19] opened 2015-03-17 00:13 UTC
Like said above. Not sure if it is your mod but it seems to only happen when stevesaddons is installed. When i go to search for a item. Some times it will just crash my client. The environment it is running in is Direwolf20 ftb pack - 1.7.10 - 1.1.1 

Server log:
[00:06:31] [Netty IO #7/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_40]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_40]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_40]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_40]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_40]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

Client Log:
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 17/03/15 00:06
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at vswe.stevesfactory.components.ScrollController.draw(ScrollController.java:195)
	at vswe.stevesfactory.components.ComponentMenuStuff.draw(ComponentMenuStuff.java:271)
	at vswe.stevesfactory.components.FlowComponent.draw(FlowComponent.java:257)
	at stevesaddons.interfaces.GuiRFManager.drawGuiContainerBackgroundLayer(GuiRFManager.java:239)
	at vswe.stevesfactory.interfaces.GuiAntiNEI.func_73863_a(GuiAntiNEI.java:73)
	at vswe.stevesfactory.interfaces.GuiBase.func_73863_a(GuiBase.java:450)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at vswe.stevesfactory.components.ScrollController.draw(ScrollController.java:195)
	at vswe.stevesfactory.components.ComponentMenuStuff.draw(ComponentMenuStuff.java:271)
	at vswe.stevesfactory.components.FlowComponent.draw(FlowComponent.java:257)
	at stevesaddons.interfaces.GuiRFManager.drawGuiContainerBackgroundLayer(GuiRFManager.java:239)
	at vswe.stevesfactory.interfaces.GuiAntiNEI.func_73863_a(GuiAntiNEI.java:73)
	at vswe.stevesfactory.interfaces.GuiBase.func_73863_a(GuiBase.java:450)

-- Screen render details --
Details:
	Screen name: stevesaddons.interfaces.GuiRFManager
	Mouse location: Scaled: (408, 263). Absolute: (816, 491)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['aokmikey'/1510211, l='MpServer', x=528.01, y=59.62, z=-214.23]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (202,64,67), Chunk: (at 10,4,3 in 12,4; contains blocks 192,0,64 to 207,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2998776 game time, 3715402 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 118 total; [EntityChicken['Chicken'/1510423, l='MpServer', x=486.66, y=65.00, z=-156.59], EntityChicken['Chicken'/1506326, l='MpServer', x=448.63, y=64.00, z=-217.41], EntityZombie['Zombie'/1538070, l='MpServer', x=483.50, y=22.00, z=-135.50], EntityZombie['Zombie'/1510431, l='MpServer', x=595.97, y=21.00, z=-255.47], EntityZombie['Zombie'/1510430, l='MpServer', x=588.31, y=16.14, z=-269.13], EntityChicken['Chicken'/267, l='MpServer', x=496.16, y=61.26, z=-277.16], EntityChicken['Chicken'/268, l='MpServer', x=501.53, y=60.23, z=-274.15], EntityChicken['Chicken'/1510425, l='MpServer', x=577.59, y=66.00, z=-169.38], EntityChicken['Chicken'/1510424, l='MpServer', x=591.63, y=65.00, z=-164.44], EntityItem['item.item.dyePowder.black'/1510149, l='MpServer', x=484.97, y=58.13, z=-253.81], EntityBat['Bat'/1351936, l='MpServer', x=498.84, y=52.10, z=-220.94], EntityClientPlayerMP['aokmikey'/1510211, l='MpServer', x=528.01, y=59.62, z=-214.23], EntityChicken['Chicken'/1510415, l='MpServer', x=557.09, y=64.00, z=-151.81], EntityChicken['Chicken'/1510414, l='MpServer', x=554.66, y=65.00, z=-143.38], EntitySheep['Sheep'/281, l='MpServer', x=503.36, y=64.00, z=-268.64], EntitySheep['Sheep'/282, l='MpServer', x=501.07, y=64.00, z=-266.29], EntitySlime['Slime'/1510412, l='MpServer', x=531.69, y=15.00, z=-153.66], EntitySheep['Sheep'/283, l='MpServer', x=504.65, y=64.00, z=-267.53], EntitySheep['Sheep'/284, l='MpServer', x=505.92, y=64.00, z=-266.15], EntityTrail['unknown'/540, l='MpServer', x=528.01, y=59.62, z=-214.23], EntityChicken['Chicken'/1510410, l='MpServer', x=508.38, y=53.00, z=-169.84], EntitySheep['Sheep'/285, l='MpServer', x=501.07, y=64.00, z=-268.84], EntityChicken['Chicken'/1510409, l='MpServer', x=557.53, y=64.00, z=-160.47], EntitySheep['Sheep'/286, l='MpServer', x=504.92, y=64.00, z=-269.93], EntitySheep['Sheep'/287, l='MpServer', x=502.38, y=64.00, z=-268.71], EntitySheep['Sheep'/288, l='MpServer', x=502.30, y=64.00, z=-266.22], EntitySkeleton['Skeleton'/1545527, l='MpServer', x=604.50, y=6.00, z=-261.50], EntitySheep['Sheep'/289, l='MpServer', x=501.09, y=64.00, z=-266.20], EntityItem['item.item.feather'/1534518, l='MpServer', x=469.81, y=60.13, z=-267.25], EntitySkeleton['Skeleton'/1545526, l='MpServer', x=604.50, y=6.00, z=-262.50], EntitySheep['Sheep'/290, l='MpServer', x=503.41, y=64.00, z=-267.51], EntitySheep['Sheep'/291, l='MpServer', x=502.23, y=64.00, z=-269.93], EntitySheep['Sheep'/292, l='MpServer', x=505.93, y=64.00, z=-265.07], EntitySheep['Sheep'/293, l='MpServer', x=503.48, y=64.00, z=-266.47], EntitySheep['Sheep'/294, l='MpServer', x=502.00, y=64.00, z=-265.07], EntitySheep['Sheep'/295, l='MpServer', x=501.09, y=64.00, z=-267.22], EntitySheep['Sheep'/296, l='MpServer', x=503.42, y=64.00, z=-269.93], EntitySpider['Spider'/1544255, l='MpServer', x=591.53, y=18.00, z=-262.75], EntitySheep['Sheep'/297, l='MpServer', x=505.55, y=64.00, z=-268.83], EntitySheep['Sheep'/298, l='MpServer', x=504.61, y=64.00, z=-266.50], EntitySheep['Sheep'/299, l='MpServer', x=501.07, y=64.00, z=-265.07], EntitySheep['Sheep'/300, l='MpServer', x=501.09, y=64.00, z=-267.65], EntitySheep['Sheep'/301, l='MpServer', x=501.07, y=64.00, z=-269.93], EntitySheep['Sheep'/302, l='MpServer', x=503.04, y=64.00, z=-265.07], EntityChicken['Chicken'/1506616, l='MpServer', x=456.59, y=64.00, z=-205.38], EntitySheep['Sheep'/303, l='MpServer', x=503.36, y=64.00, z=-269.91], EntitySheep['Sheep'/304, l='MpServer', x=505.93, y=64.00, z=-265.07], EntitySheep['Sheep'/305, l='MpServer', x=502.36, y=64.00, z=-268.90], EntityChicken['Chicken'/1510437, l='MpServer', x=577.59, y=65.00, z=-156.44], EntitySheep['Sheep'/306, l='MpServer', x=504.61, y=64.00, z=-268.80], EntitySheep['Sheep'/307, l='MpServer', x=505.93, y=64.00, z=-269.93], EntitySheep['Sheep'/308, l='MpServer', x=503.90, y=64.00, z=-265.07], EntityChicken['Chicken'/1510434, l='MpServer', x=605.47, y=66.00, z=-168.56], EntitySheep['Sheep'/309, l='MpServer', x=501.07, y=64.00, z=-269.93], EntitySheep['Sheep'/310, l='MpServer', x=504.58, y=64.00, z=-269.91], EntitySheep['Sheep'/311, l='MpServer', x=505.91, y=64.00, z=-266.25], EntitySheep['Sheep'/312, l='MpServer', x=505.55, y=64.00, z=-267.56], EntitySheep['Sheep'/313, l='MpServer', x=504.73, y=64.00, z=-265.09], EntitySheep['Sheep'/314, l='MpServer', x=502.33, y=64.00, z=-267.46], EntitySheep['Sheep'/315, l='MpServer', x=505.93, y=64.00, z=-269.93], EntityZombie['Zombie'/1510440, l='MpServer', x=448.53, y=62.17, z=-177.47], EntityChicken['Chicken'/320, l='MpServer', x=469.56, y=62.39, z=-266.56], EntityCreeper['Creeper'/1535575, l='MpServer', x=532.56, y=68.00, z=-258.42], EntityChicken['Chicken'/1510491, l='MpServer', x=457.25, y=64.00, z=-159.88], EntitySkeleton['Skeleton'/1551706, l='MpServer', x=515.50, y=18.00, z=-199.50], EntitySkeleton['Skeleton'/1551705, l='MpServer', x=510.34, y=18.00, z=-202.56], EntityBat['Bat'/1543493, l='MpServer', x=593.25, y=28.00, z=-255.75], EntitySlime['Slime'/669535, l='MpServer', x=520.22, y=18.00, z=-236.22], EntityHat['unknown'/244571, l='MpServer', x=483.47, y=62.34, z=-256.50], EntityHat['unknown'/2909, l='MpServer', x=486.66, y=65.00, z=-156.59], EntityHat['unknown'/2910, l='MpServer', x=577.59, y=65.00, z=-156.44], EntityHat['unknown'/2913, l='MpServer', x=505.92, y=64.00, z=-266.15], EntityHat['unknown'/2914, l='MpServer', x=503.42, y=64.00, z=-269.93], EntityHat['unknown'/2915, l='MpServer', x=504.61, y=64.00, z=-268.80], EntityItem['item.item.sulphur'/1524082, l='MpServer', x=535.56, y=68.13, z=-255.16], EntityZombie['Zombie'/1549691, l='MpServer', x=583.50, y=20.00, z=-262.50], EntityZombie['Zombie'/1549690, l='MpServer', x=583.56, y=20.00, z=-265.69], EntityZombie['Zombie'/1549689, l='MpServer', x=588.31, y=16.00, z=-268.31], EntityZombie['Zombie'/1549688, l='MpServer', x=583.50, y=20.00, z=-258.50], EntityBat['Bat'/998783, l='MpServer', x=504.53, y=48.70, z=-221.54], EntityBat['Bat'/1548390, l='MpServer', x=560.88, y=40.57, z=-242.84], BlueSlime['Blue Slime'/1508962, l='MpServer', x=582.63, y=22.00, z=-275.38], EntityItem['item.tile.ritualStone'/1530734, l='MpServer', x=532.22, y=62.13, z=-262.50], EntityItem['item.tile.ritualStone'/1530733, l='MpServer', x=527.78, y=63.13, z=-255.81], EntityItem['item.item.arrow'/1530732, l='MpServer', x=535.75, y=68.13, z=-259.81], EntityChicken['Chicken'/1510504, l='MpServer', x=447.47, y=65.00, z=-179.56], EntitySlime['Slime'/1243798, l='MpServer', x=526.69, y=15.03, z=-230.31], EntityCreeper['Creeper'/1542032, l='MpServer', x=604.50, y=11.00, z=-286.50], EntityBat['Bat'/1542556, l='MpServer', x=588.36, y=23.92, z=-255.53], EntityBat['Bat'/1550469, l='MpServer', x=605.41, y=30.01, z=-295.03], EntityZombie['Zombie'/1537416, l='MpServer', x=531.30, y=68.00, z=-259.70], EntityBat['Bat'/1462965, l='MpServer', x=504.25, y=55.10, z=-202.50], EntityHat['unknown'/272816, l='MpServer', x=583.50, y=20.00, z=-258.50], EntityHat['unknown'/272817, l='MpServer', x=588.31, y=16.00, z=-268.31], EntityZombie['Zombie'/1534126, l='MpServer', x=532.28, y=68.00, z=-255.44], EntityManaBurst['Mana Burst'/1552040, l='MpServer', x=518.50, y=57.70, z=-238.50], EntityBat['Bat'/1547228, l='MpServer', x=591.24, y=21.07, z=-263.07], EntityItem['item.item.egg'/1535961, l='MpServer', x=496.06, y=62.21, z=-278.23], EntityHat['unknown'/464, l='MpServer', x=528.01, y=59.62, z=-214.23], EntitySquid['Squid'/1546951, l='MpServer', x=478.66, y=60.00, z=-256.56], EntityZombie['Zombie'/1548999, l='MpServer', x=606.50, y=20.00, z=-254.50], EntitySkeleton['Skeleton'/1548998, l='MpServer', x=602.91, y=20.00, z=-255.50], EntitySquid['Squid'/1546948, l='MpServer', x=483.56, y=61.34, z=-250.53], EntitySquid['Squid'/1546947, l='MpServer', x=483.47, y=62.34, z=-256.50], EntitySquid['Squid'/1546946, l='MpServer', x=486.91, y=60.06, z=-252.94], EntitySquid['Squid'/1546955, l='MpServer', x=476.47, y=60.22, z=-247.47], EntitySquid['Squid'/1546954, l='MpServer', x=486.72, y=62.34, z=-255.88], EntitySquid['Squid'/1546953, l='MpServer', x=485.09, y=60.34, z=-257.34], EntitySquid['Squid'/1546952, l='MpServer', x=477.78, y=62.34, z=-252.50], EntityBat['Bat'/858607, l='MpServer', x=540.25, y=49.10, z=-234.50], EntityConcussionCreeper['Concussion Creeper'/1543413, l='MpServer', x=588.50, y=25.00, z=-254.00], EntityItem['item.item.dyePowder.black'/1550581, l='MpServer', x=478.72, y=61.13, z=-250.78], EntityItem['item.item.egg'/1551358, l='MpServer', x=501.25, y=60.13, z=-274.13], EntityBat['Bat'/1015038, l='MpServer', x=536.41, y=47.10, z=-237.13], EntityChicken['Chicken'/1534949, l='MpServer', x=531.38, y=66.00, z=-253.63], EntityZombie['Zombie'/1534948, l='MpServer', x=531.28, y=66.35, z=-253.65], BlueSlime['Blue Slime'/1507810, l='MpServer', x=587.78, y=20.00, z=-264.22], EntityZombie['Zombie'/1507040, l='MpServer', x=596.48, y=19.00, z=-264.55]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by hilburn** [comment] 2015-03-17 07:53
This is likely caused by SA at some point and I'll look into it, however I do need more info from you, namely:
Steve's Addon's version, content of the Manager that's crashing (in terms of commands) and whether there's any pattern in terms of searching items, inventories, fluids, tanks, rf etc

**Comment by AoKMiKeY** [comment] 2015-03-17 17:40
StevesAddons-1.7.10-0.9.7.jar - version
StevesFactoryManagerA93 - version 
http://gyazo.com/009857eb0580ecd78dd325c279f2491a -- crashed when working on that 
http://gyazo.com/e506dbef37d3d0a43d9d3d05993a199c -- crashed while trying to find the engineee < crash on the last e. I think it was finding a fucked item or something.

I am just working on automating the AE processors. 

if you need anything more then just give me a shout.

**Comment by AoKMiKeY** [comment] 2015-03-17 18:40
Okay, I have just managed to have it happen again. I will put a screen shot of the exact command i was doing. 

Okay, So i am writing a command to look at a jabba barrel though a variable. Then i typed engin+"n" and it crashed. 

http://gyazo.com/20e00061b47d43dd5485b9fbaa6651b7

**Comment by hilburn** [comment] 2015-03-18 20:15
The issue seems to be that my threading is editing the list during the render tick - I've modified this so it won't happen any more and will be fixed in the next release.

**Closed by hilburn** 2015-03-18 20:15 UTC

**Comment by AoKMiKeY** [comment] 2015-03-19 11:01
Awesome,  Thanks.
