### ISSUE TITLE
Crafting Bug in SFM

### ISSUE THREAD

**Issue by Grimjahk** [hilburn/StevesAddons#47] opened 2015-04-21 13:32 UTC
I found a Bug in SFM while playing Agrarian Skies 2. (not sure which version of SFM, but I think it was latest as it has the "Copy" function that I had not seen before. (I'm really hoping you guys can help because I love this mod, but Jadedcat pulled it from her AS2 pack for now until it gets fixed.)

Somehow, the way I set up my crafting command structure was allowing crafting to complete with insufficient materials. 

I reproduced this bug on an older copy of SFM in the current version of ME^4.

Nesting Command groups is the culprit

Layer1: Trigger and CG1(command group1)
Layer2: Node-CG2-Node
Layer3: Node-CG3-Node
Layer4: Node-Test1(CG)-Test2(CG)-Test3(CG)-Test4(CG)-Test5(CG)-Node

Test1: Node-Input-Crafter(planks->Crafting Tables)-Output-Node
Test2: Node-Input-Crafter(Sticks->Fences)-Output-Node
Test3: Node-Input-Crafter(Dirt-Compressed Dirt)-Output-Node
Test4: Node-Input-Crafter(Iron Ingot-Iron Chestplate)-Output-Node
Test5: Node-Input-Crafter(stuff-redstone Comparator)-Output-Node

With this setup the first item in the line will always work correctly, (Must have four planks to make one Crafting table) However every line after that requires only the top line of the crafting recipe to complete and at least one of the remaining materials (3 sticks will complete a fence, 3 dirt will complete a Compressed Dirt, 2 Iron Ingots will complete an Iron Chestplate, one Redstone torch, one Nether Quartz, and One Stone will produce One Comparator)

**Comment by way2muchnoise** [comment] 2015-04-21 14:30
Since @hilburn is doing a complete clean of SFM in [AFM](https://github.com/hilburn/AdvancedFactoryManager) it will probably get fixed there

**Comment by hilburn** [comment] 2015-04-21 16:13
Right - is this a SFM bug or SA bug - can you reproduce it without SA?

**Comment by Grimjahk** [comment] 2015-04-21 16:41
In Material Energy ^4 there is no SA and that is the pack I reproduced the bugs in

**Comment by hilburn** [comment] 2015-04-21 16:59
Ok - then I am unlikely to be able to fix this

**Comment by Grimjahk** [comment] 2015-04-21 17:28
Well poop.. So this bug will also be there in ASM?

**Comment by hilburn** [comment] 2015-04-22 00:18
ASM? AFM - though I might rename it to Advanced Inventory Manager for the AIM acronym

And no it will not

**Comment by Grimjahk** [comment] 2015-04-22 00:44
LOL I meant AFM... That is awesome news.. 

AIM... Well then you could say that any pack without your mod would be AIMless... 

Since I just found out about this today, I have to ask... Is it stable enough for testing? Or close to release?

**Comment by hilburn** [comment] 2015-04-22 00:46
Since I started it yesterday no - nowhere near close

Maybe after the weekend I'll have something simple but stable with the right framework in place

**Comment by Grimjahk** [comment] 2015-04-22 05:27
Well I wish you the best of luck and speed ;-)

**Comment by hilburn** [comment] 2015-04-25 16:50
I've identified this issue - is fixed as of 0.10.6

**Closed by hilburn** 2015-04-25 16:50 UTC
